// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yalla.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401113629_AddPharmacyIconUrl")]
    partial class AddPharmacyIconUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yalla.Domain.Entities.BasketPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_basket_positions_client_id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_basket_positions_medicine_id");

                    b.ToTable("basket_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<int>("WooCommerceId")
                        .HasColumnType("integer")
                        .HasColumnName("woo_commerce_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.HasIndex("WooCommerceId")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_woo_commerce_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.CheckoutRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_transaction_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_hash");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_checkout_requests_order_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_checkout_requests_status");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_checkout_requests_client_idempotency_key");

                    b.ToTable("checkout_requests", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Articul")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("articul");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid?>("Id1C")
                        .HasColumnType("uuid")
                        .HasColumnName("id_1c");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<int?>("WooCommerceId")
                        .HasColumnType("integer")
                        .HasColumnName("woo_commerce_id");

                    b.HasKey("Id");

                    b.HasIndex("Articul")
                        .IsUnique()
                        .HasDatabaseName("ix_medicines_articul")
                        .HasFilter("articul IS NOT NULL");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_medicines_category_id");

                    b.HasIndex("Id1C")
                        .IsUnique()
                        .HasDatabaseName("ix_medicines_id_1c")
                        .HasFilter("id_1c IS NOT NULL");

                    b.HasIndex("WooCommerceId")
                        .IsUnique()
                        .HasDatabaseName("ix_medicines_woo_commerce_id")
                        .HasFilter("woo_commerce_id IS NOT NULL");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.MedicineImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<bool>("IsMinimal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_minimal");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("key");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("ux_medicine_images_medicine_main")
                        .HasFilter("is_main");

                    b.HasIndex("MedicineId", "IsMinimal")
                        .IsUnique()
                        .HasDatabaseName("ux_medicine_images_medicine_minimal")
                        .HasFilter("is_minimal");

                    b.ToTable("medicine_images", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("price");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id");

                    b.HasIndex("PharmacyId")
                        .HasDatabaseName("ix_offers_pharmacy_id");

                    b.HasIndex("MedicineId", "PharmacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_offers_medicine_id_pharmacy_id");

                    b.ToTable("offers", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("client_phone_number");

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsPickup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pickup");

                    b.Property<DateTime>("OrderPlacedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("order_placed_at");

                    b.Property<decimal>("PaymentAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("payment_amount");

                    b.Property<string>("PaymentComment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("payment_comment");

                    b.Property<DateTime?>("PaymentConfirmedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_confirmed_at_utc");

                    b.Property<Guid?>("PaymentConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_confirmed_by_user_id");

                    b.Property<string>("PaymentCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasDefaultValue("TJS")
                        .HasColumnName("payment_currency");

                    b.Property<DateTime?>("PaymentExpiresAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("payment_expires_at_utc");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("Legacy")
                        .HasColumnName("payment_provider");

                    b.Property<string>("PaymentReceiverAccount")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasDefaultValue("")
                        .HasColumnName("payment_receiver_account");

                    b.Property<int>("PaymentState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("payment_state");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("payment_url");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.Property<decimal>("ReturnCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("return_cost");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.HasIndex("PaymentConfirmedByUserId");

                    b.HasIndex("PaymentState")
                        .HasDatabaseName("ix_orders_payment_state");

                    b.HasIndex("PharmacyId")
                        .HasDatabaseName("ix_orders_pharmacy_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_client_idempotency_key");

                    b.HasIndex("Status", "PaymentState", "PaymentExpiresAtUtc")
                        .HasDatabaseName("ix_orders_status_payment_state_payment_expires_at_utc");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.OrderPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_rejected");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_order_positions_medicine_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_positions_order_id");

                    b.ToTable("order_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConfirmedByPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confirmed_by_phone_number");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PaidAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("PaymentComment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("payment_comment");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("payment_url");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ReceiverAccount")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("receiver_account");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_phone_number");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_histories_order_id");

                    b.HasIndex("PaidAtUtc")
                        .HasDatabaseName("ix_payment_histories_paid_at_utc");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_payment_histories_user_id");

                    b.ToTable("payment_histories", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("client_phone_number");

                    b.Property<DateTime?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<bool>("IsPickup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_pickup");

                    b.Property<string>("PaymentComment")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("payment_comment");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payment_provider");

                    b.Property<string>("PaymentReceiverAccount")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_receiver_account");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("payment_url");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reject_reason");

                    b.Property<Guid>("ReservedOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserved_order_id");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_payment_intents_created_at_utc");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("ReservedOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_intents_reserved_order_id");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_payment_intents_state");

                    b.HasIndex("ClientId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_intents_client_idempotency_key");

                    b.ToTable("payment_intents", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentIntentPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid>("OfferPharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("offer_pharmacy_id");

                    b.Property<decimal>("OfferPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("offer_price");

                    b.Property<Guid>("PaymentIntentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_intent_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_payment_intent_positions_medicine_id");

                    b.HasIndex("OfferPharmacyId");

                    b.HasIndex("PaymentIntentId")
                        .HasDatabaseName("ix_payment_intent_positions_payment_intent_id");

                    b.ToTable("payment_intent_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Pharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_pharmacies_admin_id");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.RefundRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payment_transaction_id");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("reason");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_refund_requests_created_at_utc");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_refund_requests_order_id");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_refund_requests_status");

                    b.ToTable("refund_requests", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.SmsOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error_message");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("MsgId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("msg_id");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("state");

                    b.Property<int>("StatusSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("status_snapshot");

                    b.Property<string>("TxnId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("txn_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_sms_outbox_created_at_utc");

                    b.HasIndex("State", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_sms_outbox_state_next_attempt_at_utc");

                    b.HasIndex("OrderId", "StatusSnapshot", "PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_sms_outbox_order_status_phone");

                    b.ToTable("sms_outbox_messages", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.SmsVerificationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("attempts_remaining");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LastMsgId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_msg_id");

                    b.Property<string>("LastTxnId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("last_txn_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Purpose")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("purpose");

                    b.Property<DateTime>("ResendAvailableAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("resend_available_at_utc");

                    b.Property<int>("ResendsRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("resends_remaining");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("verified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_sms_verification_sessions_expires_at_utc");

                    b.HasIndex("Purpose", "PhoneNumber", "Status")
                        .HasDatabaseName("ix_sms_verification_sessions_purpose_phone_status");

                    b.ToTable("sms_verification_sessions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("Role");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f9a5f72-3c3d-4d3b-a4d8-1c5fd2194d4a"),
                            Name = "SuperAdmin",
                            PasswordHash = "$2a$06$qFsTGnRwnIMyAk6g4Q6tBedOweqKHvlgZHjoy0eWYF19jgFj.7NM.",
                            PhoneNumber = "919191919",
                            Role = 2,
                            user_type = "User"
                        });
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("Yalla.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("client");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyWorker", b =>
                {
                    b.HasBaseType("Yalla.Domain.Entities.User");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.HasIndex("PharmacyId")
                        .HasDatabaseName("ix_users_pharmacy_id");

                    b.HasDiscriminator().HasValue("pharmacy_worker");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.BasketPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany("BasketPositions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Category", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.CheckoutRequest", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Category", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("Yalla.Domain.ValueObjects.Atribute", "Atributes", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("type");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("value");

                            b1.Property<Guid>("medicine_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("medicine_id");

                            b1.ToTable("medicine_attributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("medicine_id");
                        });

                    b.Navigation("Atributes");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.MedicineImage", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Medicine", "Medicine")
                        .WithMany("Images")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Offer", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Medicine", null)
                        .WithMany("Offers")
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Yalla.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("PaymentConfirmedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany("Orders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.OrderPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany("Positions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Yalla.Domain.ValueObjects.OfferSnapshot", "OfferSnapshot", b1 =>
                        {
                            b1.Property<Guid>("OrderPositionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("PharmacyId")
                                .HasColumnType("uuid")
                                .HasColumnName("offer_pharmacy_id");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("offer_price");

                            b1.HasKey("OrderPositionId");

                            b1.ToTable("order_positions");

                            b1.WithOwner()
                                .HasForeignKey("OrderPositionId");
                        });

                    b.Navigation("Medicine");

                    b.Navigation("OfferSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentHistory", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentIntent", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentIntentPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Medicine", null)
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("OfferPharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.PaymentIntent", null)
                        .WithMany("Positions")
                        .HasForeignKey("PaymentIntentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.RefundRequest", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyWorker", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Medicine", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PaymentIntent", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Pharmacy", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Client", b =>
                {
                    b.Navigation("BasketPositions");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
