// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yalla.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302154321_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yalla.Domain.Entities.Medicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Articul")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("articul");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Articul")
                        .HasDatabaseName("ix_medicines_articul");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("cost");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("delivery_address");

                    b.Property<decimal>("ReturnCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("return_cost");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_orders_client_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_orders_status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Pharmacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_pharmacies_admin_id");

                    b.ToTable("pharmacies", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_pharmacy_orders_order_id");

                    b.HasIndex("PharmacyId")
                        .HasDatabaseName("ix_pharmacy_orders_pharmacy_id");

                    b.ToTable("pharmacy_orders", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<Guid>("MedicineId")
                        .HasColumnType("uuid")
                        .HasColumnName("medicine_id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<Guid?>("basket_client_id")
                        .HasColumnType("uuid")
                        .HasColumnName("basket_client_id");

                    b.HasKey("Id");

                    b.HasIndex("MedicineId")
                        .HasDatabaseName("ix_positions_medicine_id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_positions_order_id");

                    b.HasIndex("basket_client_id")
                        .HasDatabaseName("ix_positions_basket_client_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_users_phone_number");

                    b.ToTable("users", (string)null);

                    b.HasDiscriminator<string>("user_type").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.OrderRejectedPosition", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("OrderId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("order_rejected_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.PharmacyOrderPosition", b =>
                {
                    b.Property<Guid>("PharmacyOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_order_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("PharmacyOrderId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("pharmacy_order_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.PharmacyOrderRejectedPosition", b =>
                {
                    b.Property<Guid>("PharmacyOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_order_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.HasKey("PharmacyOrderId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("pharmacy_order_rejected_positions", (string)null);
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Client", b =>
                {
                    b.HasBaseType("Yalla.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("client");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyWorker", b =>
                {
                    b.HasBaseType("Yalla.Domain.Entities.User");

                    b.Property<Guid>("PharmacyId")
                        .HasColumnType("uuid")
                        .HasColumnName("pharmacy_id");

                    b.HasIndex("PharmacyId")
                        .HasDatabaseName("ix_users_pharmacy_id");

                    b.HasDiscriminator().HasValue("pharmacy_worker");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Medicine", b =>
                {
                    b.OwnsMany("Yalla.Domain.Entities.Offer", "Offers", b1 =>
                        {
                            b1.Property<Guid>("MedicineId")
                                .HasColumnType("uuid")
                                .HasColumnName("medicine_id");

                            b1.Property<Guid>("PharmacyId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("pharmacy_id");

                            b1.Property<decimal>("Price")
                                .ValueGeneratedOnAdd()
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasDefaultValue(0m)
                                .HasColumnName("price");

                            b1.Property<int>("StockQuantity")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("stock_quantity");

                            b1.HasKey("MedicineId", "PharmacyId");

                            b1.HasIndex("PharmacyId")
                                .HasDatabaseName("ix_offers_pharmacy_id");

                            b1.ToTable("offers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("MedicineId");
                        });

                    b.OwnsMany("Yalla.Domain.ValueObjects.Atribute", "Atributes", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("name");

                            b1.Property<string>("Option")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("option");

                            b1.Property<Guid>("medicine_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("medicine_id");

                            b1.ToTable("medicine_attributes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("medicine_id");
                        });

                    b.Navigation("Atributes");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyOrder", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany("PharmacyOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Pharmacy", null)
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Position", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("MedicineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.HasOne("Yalla.Domain.Entities.Client", null)
                        .WithMany("BasketPositions")
                        .HasForeignKey("basket_client_id");

                    b.OwnsOne("Yalla.Domain.Entities.Offer", "Offer", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("MedicineId")
                                .HasColumnType("uuid")
                                .HasColumnName("offer_medicine_id");

                            b1.Property<Guid>("PharmacyId")
                                .HasColumnType("uuid")
                                .HasColumnName("offer_pharmacy_id");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("offer_price");

                            b1.Property<int>("StockQuantity")
                                .HasColumnType("integer")
                                .HasColumnName("offer_stock_quantity");

                            b1.HasKey("PositionId");

                            b1.ToTable("positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("Medicine");

                    b.Navigation("Offer")
                        .IsRequired();
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.OrderRejectedPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_rejected_positions_order_id");

                    b.HasOne("Yalla.Domain.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_rejected_positions_position_id");
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.PharmacyOrderPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.PharmacyOrder", null)
                        .WithMany()
                        .HasForeignKey("PharmacyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pharmacy_order_positions_pharmacy_order_id");

                    b.HasOne("Yalla.Domain.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pharmacy_order_positions_position_id");
                });

            modelBuilder.Entity("Yalla.Infrastructure.Configurations.PharmacyOrderRejectedPosition", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.PharmacyOrder", null)
                        .WithMany()
                        .HasForeignKey("PharmacyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pharmacy_order_rejected_positions_pharmacy_order_id");

                    b.HasOne("Yalla.Domain.Entities.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pharmacy_order_rejected_positions_position_id");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.PharmacyWorker", b =>
                {
                    b.HasOne("Yalla.Domain.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Order", b =>
                {
                    b.Navigation("PharmacyOrders");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("Yalla.Domain.Entities.Client", b =>
                {
                    b.Navigation("BasketPositions");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
