services:

  front:
    build:
      context: ./yalla-farm-front
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=http://localhost:5000
        - NEXT_PUBLIC_SIGNALR_UPDATES_HUB_URL=http://localhost:5000/hubs/updates
    container_name: yalla-front
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - yalla-network

  api:
    build: ./yalla-back
    container_name: yalla-api
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - minio
    environment:
      - Database__ApplyMigrationsOnStartup=true
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=app_db;Username=postgres;Password=postgres
      - MinIo__Endpoint=minio:9000
      - MinIo__ContainerEndpoint=minio:9000
      - MinIo__AccessKey=minioadmin
      - MinIo__SecretKey=minioadmin
      - MinIo__BucketName=yalla-farm-medicines
      - MinIo__UseSsl=false
    networks:
      - yalla-network

  postgres:
    image: postgres:16
    container_name: yalla-postgres
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - yalla-network

  minio:
    image: minio/minio
    container_name: yalla-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      - yalla-network

networks:
  yalla-network:

volumes:
  postgres-data:
    external: true
  minio-data:
    external: true
