global using Moq;
global using Xunit;
global using Yalla.Application;
global using Yalla.Api;
global using Yalla.Presentation.Tests.Helpers;
global using Yalla.Domain.Entities;
global using Yalla.Domain.Enums;

global using DbAddress = Yalla.Domain.Entities.Address;
global using DbClient = Yalla.Domain.Entities.Client;
global using DbCountry = Yalla.Domain.Entities.Country;
global using DbOrder = Yalla.Domain.Entities.Order;
global using DbOrderHistory = Yalla.Domain.Entities.OrderHistory;
global using DbPharmacy = Yalla.Domain.Entities.Pharmacy;
global using DbPharmacyOrder = Yalla.Domain.Entities.PharmacyOrder;
global using DbProduct = Yalla.Domain.Entities.Product;
global using DbProductHistory = Yalla.Domain.Entities.ProductHistory;
global using DbProductProvider = Yalla.Domain.Entities.ProductProvider;
global using DbProductTemplate = Yalla.Domain.Entities.ProductTemplate;
global using DbProvider = Yalla.Domain.Entities.Provider;
global using DbReleaseForm = Yalla.Domain.Entities.ReleaseForm;
global using DbUser = Yalla.Domain.Entities.User;

global using ClientResponse = Yalla.Application.ClientDto;
global using DeliveryStatusRequest = Yalla.Application.DeliveryRequestDto;
global using IOrderRequest = Yalla.Application.IOrderDto;
global using LoginRequest = Yalla.Application.LoginRequestDto;
global using OrderCancelRequest = Yalla.Application.OrderCancelDto;
global using OrderConsultingRequest = Yalla.Application.OrderConsultingDto;
global using OrderDeliveryRequest = Yalla.Application.OrderDeliveryDto;
global using OrderFilterRequest = Yalla.Application.OrderFilterDto;
global using OrderInSearchRequest = Yalla.Application.OrderInSearchDto;
global using OrderPlacementRequest = Yalla.Application.OrderPlacementDto;
global using OrderRejectionRequest = Yalla.Application.OrderRejectionDto;
global using OrderResponse = Yalla.Application.OrderDto;
global using OrderReturnProductRequest = Yalla.Application.OrderReturnProductDto;
global using OrderWaitClientRequest = Yalla.Application.OrderWaitClientDto;
global using PackagingTypeResponse = Yalla.Application.PackagingTypeDto;
global using PackagingUnitResponse = Yalla.Application.PackagingUnitDto;
global using PaymentMethodResponse = Yalla.Application.PaymentMethodDto;
global using PharmacyOrderResponse = Yalla.Application.PharmacyOrderDto;
global using PharmacyResponse = Yalla.Application.PharmacyDto;
global using ProductProviderResponse = Yalla.Application.ProductProviderDto;
global using ProductResponse = Yalla.Application.ProductDto;
global using ProductTemplateResponse = Yalla.Application.ProductTemplateDto;
global using ReleaseFormResponse = Yalla.Application.ReleaseFormDto;
global using UpdateOrderStateRequest = Yalla.Application.UpdateStateDto;
global using UserResponse = Yalla.Application.UserDto;
